### ISSUE TITLE
Collatz benchmark running slowly

### ISSUE THREAD

**Issue by oflatt** [oflatt/eggcc#109]
The `collatz.bril` benchmark is causing eggcc to run very slowly, we should investigate and fix

**Comment by clyben** [comment]
<img width="1552" alt="image" src="https://github.com/oflatt/eggcc/assets/93016614/6c4012e2-3648-490c-b5e4-cfc74f6c80ea">
If the problem still exists, I guess it's a problem with encoding. Right now every Project records the region it owns and could be the same region every time. This program unfortunately has 3 nested region and each region have too many Projects, so the size of representation goes expoential. This program took about 80000 char in egglog encoding.

**Comment by oflatt** [comment]
Solved by #115
