### ISSUE TITLE
PEG cannot distinguish between different projections into a function call that has multiple return values

### ISSUE THREAD

**Issue by yihozhang** [oflatt/eggcc#118]
In #117, we have to disable [this check](https://github.com/oflatt/eggcc/blob/5757700b36c5798550ba338b9f3da9b554aba0ff/src/peg/simulate.rs#L155) for the following program with `--peg` flag.
```
@main {
    a: int = const 0;
    c: int = call @inc a;
    print c;
}

@inc (x: int): int {
    one: int = const 1;
    res: int = add one x;
    ret res;
}
```

This is because the state edge to `print` in this example is basically `(Project 1 (Call "inc" ...))` (obtaining the state edge out of the call), and in our current PEG implementation there is no way to distinguish this between `(Project 0 (Call "inc" ...))` which gets the actual return value.

**Comment by Alex-Fischman** [comment]
After talking with Oliver we've decided to remove the PEG interpreter for now and add a tag so we can find it later. Fixing this issue would require refactoring Call out of Expr and into Body, and would introduce the same linearity problems that RVSDGs have right now.
